services:

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/nginx/certs
    networks:
      - backend-net
      - gui-net

  incident-manager-frontend:
    container_name: incident-manager-frontend
    image: incident-manager-frontend:dev
    restart: on-failure
    build:
      context: incident_manager2000
      dockerfile: Dockerfile
    networks:
      - backend-net

  incident-manager:
    container_name: incident-manager
    image: incident-manager:dev
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/incident-manager
      SPRING_DATASOURCE_USERNAME: bsk
      SPRING_DATASOURCE_PASSWORD: bsk
      SERVER_PORT: 8080
    networks:
      - backend-net
      - db-net

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: bsk
      POSTGRES_PASSWORD: bsk
      POSTGRES_DB: incident-manager
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      - db-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: bsk@bsk.pl
      PGADMIN_DEFAULT_PASSWORD: bsk
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db-net
      - gui-net

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.4.7
    restart: on-failure
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: bsk
      KC_BOOTSTRAP_ADMIN_PASSWORD: bsk
      KC_HOSTNAME: https://bskprojekt.kacperklimas.com/keycloak/
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
    command: start
    networks:
      - backend-net
      - db-net

  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare
    restart: on-failure
    volumes:
      - ./certbot/cloudflare.ini:/opt/certbot/cloudflare.ini
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --non-interactive --agree-tos --dns-cloudflare --dns-cloudflare-credentials cloudflare.ini -d *.bskprojekt.kacperklimas.com -d bskprojekt.kacperklimas.com

volumes:
  postgresql:
  pgadmin:
  certbot-etc:
  certbot-var:

networks:
  backend-net:
  db-net:
  gui-net: