services:

  incident-manager-frontend:
    container_name: incident-manager-frontend
    image: incident-manager-frontend:dev
    restart: on-failure
    build:
      context: incident_manager2000
      dockerfile: Dockerfile
    environment:
      NEXTAUTH_SECRET: B2XcRcb20Eq1tSRCjyIG9rCKp+Kbtq/dkauaBZbbRxU=
      MICROSOFT_ID: 2f84a070-ee00-4815-afbb-632d2edb9f09
      MICROSOFT_SECRET: vJJ8Q~955jXcXY1eeJXyBS0QVRbcFfzKNtnT7drN
      BACKEND_URL : http://localhost:8082/api
    networks:
      - backend-net
    ports:
      - "3000:3000"

  incident-manager:
    container_name: incident-manager
    image: incident-manager:dev
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/incident-manager
      SPRING_DATASOURCE_USERNAME: bsk
      SPRING_DATASOURCE_PASSWORD: bsk
      SERVER_PORT: 8082
    networks:
      - backend-net
      - db-net
    ports:
      - "8082:8082"

  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: bsk
      POSTGRES_PASSWORD: bsk
      POSTGRES_DB: incident-manager
    volumes:
      - postgresql:/var/lib/postgresql
    networks:
      - db-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: bsk@bsk.pl
      PGADMIN_DEFAULT_PASSWORD: bsk
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db-net
      - gui-net

volumes:
  postgresql:
  pgadmin:

networks:
  backend-net:
  db-net:
  gui-net: